### ISSUE TITLE
Remove the Plugin context class

### ISSUE THREAD

**Issue by spacedmonkey** [10up/plugin-check#123] opened 2023-03-31 16:13 UTC
### Is your enhancement related to a problem? Please describe.

Remove the plugin context class, as is no longer used for anything with in the codebase. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felixarntz** [comment] 2023-03-31 16:57
The idea for that class is that it should be used anywhere that we need to access the plugin checker plugin's own basename, path, or URL. Looks like we've since introduced constants like `WP_PLUGIN_CHECK_PLUGIN_DIR_URL` instead.

Either works, I'd argue the class approach is cleaner as it decouples from the constant (constants are terrible when writing unit tests for example). But let's discuss that. Either we should remove the constants and use the class as intended, or we should remove the class and use constants.

**Comment by spacedmonkey** [comment] 2023-03-31 17:29
My recommendation, would be remove this class for now and introduce it when there is a use for it. At the moment, the case is not used for anything, which is just wasteful.

**Comment by felixarntz** [comment] 2023-03-31 18:05
Well, it's not used, but there are still use-cases, and I think it should be used instead of the constants.

**Comment by swissspidy** [comment] 2024-09-27 15:35
Closing as maybelater due to lack of traction. So far the current setup seems to be working fine, no need to change anything for the sake of change.

**Closed as not planned by swissspidy** 2024-09-27 15:35 UTC
Labels: Code Quality
