### ISSUE TITLE
Create Enqueued_Scripts_In_Footer_Check

### ISSUE THREAD

**Issue by mehulkaklotar** [10up/plugin-check#41] opened 2022-12-12 07:13 UTC
## Description

Checks registered and enqueued scripts in the plugin and warns if the $in_footer parameter is false. It is encouraged that any non-essential scripts are loaded in the footer to prevent render-blocking on the page. It will also check that the version parameter is set to a non-falsy value. Using versions in the scripts can be beneficial for performance and cache busting. This will use the existing WordPress.WP.EnqueuedResourceParameters sniff in the [WordPress Coding Standards](https://github.com/WordPress/WordPress-Coding-Standards/).

## Acceptance Criteria

- Class `Enqueued_Scripts_In_Footer_Check` should be created and exists at `includes/Checker/Checks`
- Class `Enqueued_Scripts_In_Footer_Check` should extend the `Runtime_Check` abstract class which extends `Check` interface
- Property `$violation` code should be `warning`
- Method `run` should be implemented from the `Runtime_Check` abstract class if needed
- `Check_Result $check_result` should be used from the `run` method parameter to append the results

## Test Coverage

- `Enqueued_Scripts_In_Footer_Check` class is expected to extend `Runtime_Check` class
- `Enqueued_Scripts_In_Footer_Check` class is expected to be instance of `Runtime_Check` class
- `run` method expected to append the audit results to `$check_result`

**Comment by vishalkakadiya** [comment] 2023-02-09 05:47
@jjgrainger This is a duplicate of #22, we can close this issue as I have already updated the AC for #22. Thank you!

**Comment by felixarntz** [comment] 2023-05-24 21:51
Closed as duplicate

**Closed as completed by felixarntz** 2023-05-24 21:51 UTC
Labels: [Type] Enhancement, Checks
